/**
 * Regenerates src/components/icons.tsx from Phosphor's light-weight glyphs.
 *
 *   node scripts/build-icons.mjs
 *
 * Why vendor them at all: @phosphor-icons/react inlines all six weights of
 * every icon it exports, which costs ~170 KB of bundle for the ~60 glyphs this
 * console draws — and it only ever draws the light weight. Extracting just
 * those paths keeps the same artwork at a fraction of the size and leaves no
 * runtime dependency. @phosphor-icons/react stays a devDependency purely so
 * this script has something to read.
 *
 * To add a glyph: put its Phosphor name in ICONS below, keyed by the name this
 * console exports it as, then re-run. Glyph artwork is MIT licensed.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const DEFS = join(ROOT, 'node_modules', '@phosphor-icons', 'react', 'dist', 'defs');
const OUT = join(ROOT, 'src', 'components', 'icons.tsx');

/** Exported name -> Phosphor glyph name, grouped as the file reads. */
const ICONS = {
  Navigation: {
    NavDashboard: 'SquaresFour',
    NavUsers: 'Users',
    NavProducts: 'Package',
    NavOrders: 'Receipt',
    NavCategories: 'CirclesThreePlus',
    NavBanners: 'Image',
    NavCoupons: 'Gift',
    NavPayments: 'Wallet',
    NavDelivery: 'Truck',
    NavReturns: 'ArrowsLeftRight',
    NavDeliverySettings: 'Sliders',
    NavReferrals: 'ShareNetwork',
    NavMessages: 'Envelope',
  },
  Actions: {
    ArrowLeft: 'ArrowLeft',
    ArrowRight: 'ArrowRight',
    ArrowUpRight: 'ArrowUpRight',
    ChevronRight: 'CaretRight',
    ChevronDown: 'CaretDown',
    Plus: 'Plus',
    Pencil: 'PencilSimple',
    Trash: 'Trash',
    Close: 'X',
    Check: 'Check',
    Copy: 'Copy',
    Search: 'MagnifyingGlass',
    Refresh: 'ArrowsClockwise',
    Upload: 'UploadSimple',
    LinkIcon: 'Link',
    ExternalLink: 'ArrowSquareOut',
    Settings: 'SlidersHorizontal',
    LogIn: 'SignIn',
    LogOut: 'SignOut',
    Star: 'Star',
    Spinner: 'SpinnerGap',
  },
  'Status & meaning': {
    Info: 'Info',
    AlertCircle: 'WarningCircle',
    AlertTriangle: 'Warning',
    XCircle: 'XCircle',
    CheckCircleIcon: 'CheckCircle',
    ShieldCheck: 'ShieldCheck',
    BadgeCheck: 'SealCheck',
    Trophy: 'Trophy',
    Clock: 'ClockCounterClockwise',
    TrendUpIcon: 'TrendUp',
    ChartIcon: 'ChartLineUp',
    Rupee: 'CurrencyInr',
  },
  Objects: {
    Package: 'Package',
    Truck: 'Truck',
    Receipt: 'Receipt',
    ReceiptCancelled: 'ReceiptX',
    ShoppingBag: 'ShoppingBag',
    Wallet: 'Wallet',
    Gift: 'Gift',
    Mail: 'Envelope',
    MailOpen: 'EnvelopeOpen',
    AtSign: 'At',
    Share: 'ShareNetwork',
    UserIcon: 'UserCircle',
    StoreIcon: 'Storefront',
    TagIcon: 'Tag',
    BellIcon: 'Bell',
  },
  'Media & forms': {
    ImageIcon: 'Image',
    ImageOff: 'ImageBroken',
    ImagePlus: 'ImageSquare',
    Film: 'FilmSlate',
    Play: 'Play',
    Scissors: 'Scissors',
    Ratio: 'CornersOut',
    Scan: 'CornersOut',
    HardDrive: 'HardDrives',
    Lock: 'Lock',
    Eye: 'Eye',
    EyeOff: 'EyeSlash',
    Indent: 'ArrowElbowDownRight',
    Palette: 'PaintBrushBroad',
  },
};

/** Pulls the `light` entry out of a glyph's weight map. */
function lightPaths(name) {
  const file = join(DEFS, `${name}.es.js`);
  if (!existsSync(file)) throw new Error(`No Phosphor def for "${name}" — check the spelling.`);
  const body = readFileSync(file, 'utf8');

  const block = body.match(/\[\s*"light",(.*?)\n {2}\]/s);
  if (!block) throw new Error(`No light weight in "${name}".`);

  // A few glyphs are drawn with more than one path; keep them in order.
  const ds = [...block[1].matchAll(/"path",\s*\{\s*d:\s*"([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) throw new Error(`No path data in "${name}".`);
  return ds;
}

const rule = (title) => `/* ── ${title} ${'─'.repeat(Math.max(3, 70 - title.length))} */`;

const header = `/**
 * The console's icon set — Phosphor's \`light\` glyphs, vendored.
 *
 * GENERATED by scripts/build-icons.mjs — edit that, not this.
 *
 * Only the light weight is used (at 16–20px on an OLED surface a 2px stroke
 * reads as a smudge, while a hairline stays precise), so only those paths are
 * vendored: the same artwork as @phosphor-icons/react at a fraction of the
 * weight, and no runtime dependency.
 *
 * Glyph artwork: Phosphor Icons, MIT licensed.
 */
import type { ComponentType } from 'react';

export interface IconProps {
  size?: number;
  className?: string;
}

export type Icon = ComponentType<IconProps>;

/**
 * Phosphor draws on a 256x256 grid. \`currentColor\` means an icon always takes
 * the colour of whatever it sits in, so no call site ever passes a fill.
 */
function glyph(paths: readonly string[]): Icon {
  const Glyph = ({ size = 18, className }: IconProps) => (
    <svg
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill="currentColor"
      className={className}
      aria-hidden="true"
      focusable="false"
    >
      {paths.map((d, i) => (
        <path key={i} d={d} />
      ))}
    </svg>
  );
  return Glyph;
}
`;

const needed = [...new Set(Object.values(ICONS).flatMap(g => Object.values(g)))].sort();

const data = needed
  .map(name => {
    const ds = lightPaths(name).map(d => `  '${d}',`).join('\n');
    return `const d${name} = [\n${ds}\n] as const;`;
  })
  .join('\n\n');

const groups = Object.entries(ICONS)
  .map(([title, entries]) => {
    const lines = Object.entries(entries)
      .map(([exported, real]) => `export const ${exported} = glyph(d${real});`)
      .join('\n');
    return `${rule(title)}\n${lines}`;
  })
  .join('\n\n');

const file = `${header}\n${rule('Glyph data (Phosphor, light weight)')}\n\n${data}\n\n${groups}\n`;
writeFileSync(OUT, file, 'utf8');

const bytes = needed.reduce((n, name) => n + lightPaths(name).join('').length, 0);
console.log(`Wrote ${OUT}`);
console.log(`  ${needed.length} glyphs, ${Object.values(ICONS).flatMap(Object.keys).length} exports, ${(bytes / 1024).toFixed(1)} KB of path data`);
